# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Black - Python code formatter
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  # Ruff - Fast Python linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Local hooks
  - repo: local
    hooks:
      # Run unit tests
      - id: pytest-unit-tests
        name: pytest unit tests
        entry: uv run pytest tests/ -v -m "unit or not integration" -x
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

# Configuration
default_stages: [pre-commit]
fail_fast: false