# CLI Command Options Configuration
# This file defines available options for slash commands

commands:
  mode:
    description: "Change developer mode"
    options:
      - name: general
        description: "General conversation and assistance"
      - name: code
        description: "Optimized for writing new code"
      - name: debug
        description: "Focus on error analysis"
      - name: explain
        description: "Detailed code explanations"
      - name: review
        description: "Security and code quality review"
      - name: refactor
        description: "Code improvement suggestions"
      - name: plan
        description: "Architecture planning and system design"

  provider:
    description: "Switch provider"
    options:
      - name: oci_genai
        description: "Oracle Cloud Infrastructure GenAI"
      - name: ollama
        description: "Local models via Ollama (coming soon)"
      - name: openai
        description: "OpenAI GPT models (coming soon)"
      - name: litellm
        description: "100+ providers via LiteLLM (coming soon)"

  session:
    description: "Manage sessions"
    options:
      - name: save
        description: "Save current conversation"
      - name: load
        description: "Load a saved conversation"
      - name: last
        description: "Load the most recent session"
      - name: list
        description: "List all saved sessions"
      - name: branch
        description: "Create a branch from current conversation"
      - name: delete
        description: "Delete a saved session"
      - name: delete-all
        description: "Delete all sessions (use --auto-only for just auto-saved)"
      - name: rename
        description: "Rename a session"
      - name: info
        description: "Show session details"
      - name: search
        description: "Search sessions"

  theme:
    description: "Change UI theme"
    options:
      - name: default
        description: "Default color scheme"
      - name: dark
        description: "Dark mode optimized"
      - name: light
        description: "Light terminal theme"
      - name: minimal
        description: "Minimal colors"
      - name: vibrant
        description: "High contrast colors"

  export:
    description: "Export conversation"
    options:
      - name: markdown
        description: "Export as Markdown file"
      - name: json
        description: "Export as JSON with metadata"
      - name: txt
        description: "Export as plain text"
      - name: html
        description: "Export as HTML with syntax highlighting"

  tools:
    description: "Manage MCP tools"
    options:
      - name: list
        description: "List available MCP tools"
      - name: enable
        description: "Enable specific tools"
      - name: disable
        description: "Disable specific tools"
      - name: config
        description: "Configure tool settings"
      - name: status
        description: "Show tool status"